In [24]:
import random

def cxPartialyMatched(ind1, ind2):
    """Executes a partially matched crossover (PMX) on the input individuals.
    The two individuals are modified in place. This crossover expects
    :term:`sequence` individuals of indices, the result for any other type of
    individuals is unpredictable.

    :param ind1: The first individual participating in the crossover.
    :param ind2: The second individual participating in the crossover.
    :returns: A tuple of two individuals.

    Moreover, this crossover generates two children by matching
    pairs of values in a certain range of the two parents and swapping the values
    of those indexes. For more details see [Goldberg1985]_.

    This function uses the :func:`~random.randint` function from the python base
    :mod:`random` module.

    .. [Goldberg1985] Goldberg and Lingel, "Alleles, loci, and the traveling
       salesman problem", 1985.
    """
    size = min(len(ind1), len(ind2))
    p1, p2 = [0] * size, [0] * size

    # Initialize the position of each indices in the individuals
    for i in range(size):
        p1[ind1[i]] = i
        p2[ind2[i]] = i
    # Choose crossover points
    # cxpoint1 = random.randint(0, size)
    # cxpoint2 = random.randint(0, size - 1)
    # if cxpoint2 >= cxpoint1:
    #     cxpoint2 += 1
    # else:  # Swap the two cx points
    #     cxpoint1, cxpoint2 = cxpoint2, cxpoint1
    cxpoint1=1
    cxpoint2=4

    # Apply crossover between cx points
    for i in range(cxpoint1, cxpoint2):
        # Keep track of the selected values
        temp1 = ind1[i]
        temp2 = ind2[i]
        # Swap the matched value
        ind1[i], ind1[p1[temp2]] = temp2, temp1
        ind2[i], ind2[p2[temp1]] = temp1, temp2
        # Position bookkeeping
        print(p1)
        p1[temp1], p1[temp2] = p1[temp2], p1[temp1]
        p2[temp1], p2[temp2] = p2[temp2], p2[temp1]
        print(p1)

    return ind1, ind2

In [25]:
print(cxPartialyMatched([0,1,5,4,3,2],[4,2,3,5,1,0]))

[0, 1, 5, 4, 3, 2]
[0, 5, 1, 4, 3, 2]
[0, 5, 1, 4, 3, 2]
[0, 5, 1, 2, 3, 4]
[0, 5, 1, 2, 3, 4]
[0, 5, 1, 3, 2, 4]
([0, 2, 4, 3, 5, 1], [3, 1, 5, 4, 2, 0])


In [54]:
# Function to find the index of a city in the tour array
def find_city(city_name, n_city, tour):
    j = 0
    while j < n_city and tour[j] != city_name:
        j += 1
    return j

# Function to swap two cities in a tour array
def swap_city(city_pos1, city_pos2, tour):
    temp = tour[city_pos1]
    tour[city_pos1] = tour[city_pos2]
    tour[city_pos2] = temp

# Procedure to perform crossover on two tours
def cross_tour(n_city, lo_cross, hi_cross, tour1_old, tour2_old):
    hi_test = hi_cross + 1
    if hi_test > n_city:
        hi_test = 1
    
    # Initialize new tours as copies of the old tour
    tour1_new = tour1_old[:]
    tour2_new = tour2_old[:]
    
    if lo_cross < hi_cross and lo_cross < hi_test:
        j = lo_cross
        while j < hi_test:
            # Perform mapped crossover on both tours
                            #szukamy indeksu ind1[index] w child 2 i jego swapujemy
            
            swap_city(j, find_city(tour1_old[j], n_city, tour2_new), tour2_new)
            print(j,find_city(tour2_old[j], n_city, tour1_new),tour2_old[j])
            swap_city(j, find_city(tour2_old[j], n_city, tour1_new), tour1_new)
            print(tour1_new)
            j += 1
            if j > n_city:
                break
    
    print(tour1_new,tour2_new)


In [35]:
import numpy as np

def PMX(ind1, ind2):
    # gene=np.random.randint(1,len(ind1),2)
    # start=min(gene)-1
    # end=max(gene)
    start=1
    end=4
    child1=ind1.copy()
    child2=ind2.copy()

    # ordering1=np.zeros(len(ind1),dtype=int)
    # ordering2=np.zeros(len(ind1),dtype=int)

    # the genes are numerical and distinct, so this is fine to avoid searching later
    #this is the inverese permutation
    # for index,x in np.ndenumerate(ind1):
    #     #print(x,index)
    #     ordering1[x]=index[0]
    # for index, x in np.ndenumerate(ind2):
    #     ordering2[x]=int(index[0])
    ordering1=np.argsort(ind1)
    ordering2=np.argsort(ind2)
    #print(ordering1)
    for index in range(start,end):
        print(ordering1[ind1[index]])


    for index in range(start,end):
        #print(index)
        
        child2[index],child2[ordering2[ind1[index]]]=child2[ordering2[ind1[index]]],child2[index]
        #print(child1[index],child1[ordering1[ind2[index]]],ordering1[ind2[index]],ind2[index])
        child1[index],child1[ordering1[ind2[index]]]=child1[ordering1[ind2[index]]],child1[index]
        #print(child1)
        #ten poniżej z prawej jest poprawny, orderingiem, ale boli w oczy w taki sposób
        #print(ordering1)
        #print(ordering1[child1[index]],ordering1[child1[ordering1[ind2[index]]]])
        found1=ordering1[ind2[index]]
        print(ordering1[child1[index]],ordering1[child1[ordering1[ind2[index]]]])
        ordering1[child1[index]],ordering1[child1[found1]]=ordering1[child1[found1]],ordering1[child1[index]]
        print(ordering1[child1[index]],ordering1[child1[ordering1[ind2[index]]]])
        ordering2[child2[index]],ordering2[child2[ordering2[ind1[index]]]]=ordering2[child2[ordering2[ind1[index]]]],ordering2[child2[index]]
        print(ordering1)
        #print('###########')
        #print(ind2)
        #print('###########')
        
    return child1,child2

In [38]:
def PMX_final(ind1, ind2):
    # gene=np.random.randint(1,len(ind1),2)
    # start=min(gene)-1
    # end=max(gene)
    start=1
    end=4
    child1=ind1.copy()
    child2=ind2.copy()
    #inverse permutation
    ordering1=np.argsort(ind1)
    ordering2=np.argsort(ind2)

    for index in range(start,end):

        found1=ordering1[ind2[index]]
        found2=ordering2[ind1[index]]
        #swap the value at index with the value of the other parent at index (found in oneself)
        child2[index],child2[found2]=child2[found2],child2[index]
        child1[index],child1[found1]=child1[found1],child1[index]
        #update the positions of elements
        ordering1[child1[index]],ordering1[child1[found1]]=ordering1[child1[found1]],ordering1[child1[index]]
        ordering2[child2[index]],ordering2[child2[found2]]=ordering2[child2[found2]],ordering2[child2[index]]
        #print(ordering1[child1[index]],ordering1[child1[ordering1[ind2[index]]]])
        #print(ordering1)
    return child1,child2

In [39]:
print(PMX_final([0,1,5,4,3,2],[4,2,3,5,1,0]))

([0, 2, 3, 5, 4, 1], [3, 1, 5, 4, 2, 0])


In [36]:
print(PMX([0,1,5,4,3,2],[4,2,3,5,1,0]))

1
2
3
5 1
1 1
[0 5 1 4 3 2]
4 2
2 2
[0 5 1 2 3 4]
4 3
3 3
[0 5 1 2 4 3]
([0, 2, 3, 5, 4, 1], [3, 1, 5, 4, 2, 0])


In [ ]:
def PMX(ind1, ind2):
    gene=np.random.randint(1,len(ind1),2)
    start=min(gene)-1
    end=max(gene)
    ordering1=np.zeros(len(ind1))
    ordering2=np.zeros(len(ind1))

    # the genes are numerical and distinct, so this is fine to avoid searching later
    for index, x in np.ndenumerate(ind1):
        ordering1[x]=index[0]
    for index, x in np.ndenumerate(ind2):
        ordering2[x]=index[0]
    
    for index, x in np.ndenumerate(ind1[start:end]):
        ind1[index]=ind2[index]
        ind2[index]=x
        ind2[ordering2[x]]=ind1[index]

In [55]:
#print(cxPartialyMatched([1,2,8,7,6,3],[7,3,6,8,2,1]))
cross_tour(len([0,1,5,4,3,2]),1,3,[0,1,5,4,3,2],[4,2,3,5,1,0])

1 5 2
[0, 2, 5, 4, 3, 1]
2 4 3
[0, 2, 3, 4, 5, 1]
3 4 5
[0, 2, 3, 5, 4, 1]
[0, 2, 3, 5, 4, 1] [3, 1, 5, 4, 2, 0]
